### ISSUE TITLE
Unable to add mapster via nuget

### ISSUE THREAD

**Issue by Amit1150** [eswann/Mapster#59] opened 2016-04-02 16:04 UTC
Hello, 

I'm trying to add mapster via nuget, But every time it failed to install with error 

> Object reference not set to an instance of an object.

I'm using VS2015 and .Net 4.5.
Here is screenshot. 

![error](https://cloud.githubusercontent.com/assets/9916812/14227416/9e3a4668-f91a-11e5-88c8-adfa2023695f.png)

**Comment by chaowlert** [comment] 2016-04-25 13:08
Hi @Amit1150,

Sorry for late reply, I cannot reproduce.

**Comment by chaowlert** [comment] 2016-04-25 13:11
I will close this first, since it shouldn't relate to the library.

**Closed by chaowlert** 2016-04-25 13:11 UTC
